import streamlit as st
import requests

st.set_page_config(page_title="Note Generator", layout="centered")
st.title("📝 Note Generator")
st.markdown("Upload a `.txt` file of unstructured patient notes and get a structured output generated by AI Agent.")

uploaded_file = st.file_uploader("Upload a text file", type="txt")

if uploaded_file:
    st.success(f"Uploaded: {uploaded_file.name}")
    st.txt("uploaded_file")
    with st.spinner("Generating note via AI agent..."):

        # Prepare file for n8n webhook
        files = {
            "file": (uploaded_file.name, uploaded_file.getvalue(), "text/plain")
        }

        # POST to your n8n Cloud webhook
        webhook_url = "https://sonudemo07.app.n8n.cloud/webhook/5f17edc7-7a68-4e7a-9495-4ce0554f454c"

        try:
            response = requests.post(webhook_url, files=files)

            if response.status_code == 200:
                soap_note = response.json().get("soapNote", "No note returned.")
                st.subheader("📋 Generated Note")
                st.text_area("Output", soap_note, height=400)
            else:
                st.error(f"Failed with status {response.status_code}: {response.text}")

        except Exception as e:
            st.error(f"An error occurred: {e}")
